version: "3.2"
services:
  my-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cv-service
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: cv-service
      POSTGRES_PASSWORD: root
    volumes:
      - "pg-data:/var/lib/postgresql/data"
#    networks:
#      - local

volumes:
  pg-data: {}

#networks:
#  local:
#    driver: bridge